# Generated by Django 5.2.1 on 2025-06-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
